spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bicarb
    username: bicarb
    password: bicarb

logging:
  level:
    org.bicarb.core: info
    org.illyasviel.elide: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql: info
    com.yahoo.elide.datastores.hibernate5.porting.SessionWrapper: info
  file: bicarb.log
  path: logs
